import { buildCatalogue } from '../data/catalogue'
import { UnsupportedOperation, type IndexedBook, type LayoutDocument, type LibraryService } from './types'

const ROOT_KEY = 'library3d.root'
const LAYOUT_KEY = 'library3d.layout'
const WORLD_KEY = 'library3d.world'
const WORLD_STAMP_KEY = 'library3d.world.stamp'

/**
 * Plain-browser driver: no filesystem, a generated stand-in library.
 *
 * It exists so the scene can be developed and smoke tested headlessly without
 * launching the desktop shell. The books are openly fake — the HUD says so —
 * rather than pretending an empty index is your collection.
 *
 * The future Linux-hosted build replaces this with an HTTP driver against a
 * server-side indexer: same interface, real capabilities.
 */
/** Enough to fill the shelves, so the room looks like a library rather than a
 *  few stocked corners. Roughly 14 cases x 5 rows at typical spine widths. */
const PLACEHOLDER_COUNT = 1700

/**
 * The one book here that is a real file rather than a title on a spine.
 *
 * It is served from `public/` (generated by `npm run assets`), which is what
 * lets read mode — page cache, turn, commit — run under the headless smoke
 * tests instead of only under `test:desktop`.
 */
export const SAMPLE_BOOK_ID = 'sample-book'
const SAMPLE_BOOK_URL = 'sample-book.pdf'

const SAMPLE: IndexedBook = {
  id: SAMPLE_BOOK_ID,
  path: SAMPLE_BOOK_URL,
  format: 'pdf',
  title: 'The Shelf as Argument',
  author: 'A. Sample',
  cover: null,
  pageCount: 12,
  sizeBytes: 24_000,
  indexedAt: 0,
}

const PLACEHOLDERS: IndexedBook[] = buildCatalogue(PLACEHOLDER_COUNT).map((book, i) => ({
  id: book.id,
  path: `placeholder://${book.id}`,
  format: i % 4 === 0 ? 'epub' : 'pdf',
  title: book.title,
  author: book.author,
  cover: null,
  pageCount: 80 + ((i * 37) % 400),
  sizeBytes: 1024 * (200 + ((i * 13) % 4000)),
  indexedAt: 0,
}))

/**
 * Stand in for someone editing `library.json` and saving it.
 *
 * The browser build has no file to watch, so the world lives in localStorage and
 * the stamp is bumped by hand. That is what lets the smoke tests exercise live
 * reload and the reconciliation rules — which are the parts most likely to lose
 * somebody's arrangement, and so the parts most worth covering.
 */
export function setWorldText(text: string) {
  localStorage.setItem(WORLD_KEY, text)
  localStorage.setItem(WORLD_STAMP_KEY, `${text.length}:${nextStamp()}`)
}

let stampCounter = 0
const nextStamp = () => (stampCounter += 1)

export const browserDriver: LibraryService = {
  kind: 'browser',
  canPickFolder: false,
  canIndex: false,

  async getRoot() {
    return localStorage.getItem(ROOT_KEY)
  },

  async setRoot(path) {
    localStorage.setItem(ROOT_KEY, path)
  },

  async pickRoot() {
    return null
  },

  async scan() {
    return { found: PLACEHOLDERS.length, added: 0, unchanged: PLACEHOLDERS.length, removed: 0, failed: 0 }
  },

  onScanProgress() {
    return () => {}
  },

  async listBooks() {
    return [SAMPLE, ...PLACEHOLDERS]
  },

  async readBook(id) {
    if (id !== SAMPLE_BOOK_ID) throw new UnsupportedOperation(`reading ${id}`, 'browser')
    const response = await fetch(SAMPLE_BOOK_URL)
    // A missing sample means `npm run assets` has not run; say so rather than
    // handing pdf.js an HTML 404 page and letting it fail obscurely.
    if (!response.ok) throw new Error(`${SAMPLE_BOOK_URL} is missing — run \`npm run assets\``)
    return new Uint8Array(await response.arrayBuffer())
  },

  async saveRenderedCover(id) {
    throw new UnsupportedOperation(`caching a cover for ${id}`, 'browser')
  },

  async loadWorld() {
    return localStorage.getItem(WORLD_KEY)
  },

  async writeDefaultWorld(text) {
    if (localStorage.getItem(WORLD_KEY) !== null) return false
    setWorldText(text)
    return true
  },

  async worldStamp() {
    return localStorage.getItem(WORLD_STAMP_KEY)
  },

  async savePaths() {
    // There is no filesystem here; name the storage honestly rather than
    // inventing a path that does not exist. On the desktop these are
    // `<your library folder>/.library/library.json` and `.../books.json`.
    return { world: 'localStorage: library3d.world', layout: 'localStorage: library3d.layout' }
  },

  async loadLayout() {
    const stored = localStorage.getItem(LAYOUT_KEY)
    return stored ? (JSON.parse(stored) as LayoutDocument) : null
  },

  async saveLayout(layout) {
    localStorage.setItem(LAYOUT_KEY, JSON.stringify(layout))
  },

  assetUrl(path) {
    return path
  },
}
