import { buildCatalogue } from '../data/catalogue'
import {
  UnsupportedOperation,
  type AnnotationsDocument,
  type IndexedArtwork,
  type IndexedBook,
  type IndexedRom,
  type IndexedTape,
  type IndexedTrack,
  type LayoutDocument,
  type LibraryService,
  type AmbienceState,
} from './types'

const ROOT_KEY = 'kleib3ry.root'
const LAYOUT_KEY = 'kleib3ry.layout'
const WORLD_KEY = 'kleib3ry.world'
const WORLD_STAMP_KEY = 'kleib3ry.world.stamp'
const AMBIENCE_KEY = 'kleib3ry.ambience'
const ANNOTATIONS_KEY = 'kleib3ry.annotations'

/**
 * Plain-browser driver: no filesystem, a generated stand-in library.
 *
 * It exists so the scene can be developed and smoke tested headlessly without
 * launching the desktop shell. The books are openly fake — the HUD says so —
 * rather than pretending an empty index is your collection.
 *
 * The future Linux-hosted build replaces this with an HTTP driver against a
 * server-side indexer: same interface, real capabilities.
 */
/** Enough to fill the shelves, so the room looks like a library rather than a
 *  few stocked corners. Roughly 14 cases x 5 rows at typical spine widths. */
const PLACEHOLDER_COUNT = 1700

/**
 * The two books here that are real files rather than titles on spines.
 *
 * One of each format, served from `public/` (generated by `npm run assets`),
 * which is what lets read mode — page cache, turn, commit, and the type setter
 * an EPUB goes through — run under the headless smoke tests instead of only
 * under `test:desktop`.
 */
export const SAMPLE_BOOK_ID = 'sample-book'
export const SAMPLE_EPUB_ID = 'sample-epub'
const SAMPLE_FILES: Record<string, string> = {
  [SAMPLE_BOOK_ID]: 'sample-book.pdf',
  [SAMPLE_EPUB_ID]: 'sample-book.epub',
}

const SAMPLE: IndexedBook = {
  id: SAMPLE_BOOK_ID,
  path: SAMPLE_FILES[SAMPLE_BOOK_ID]!,
  format: 'pdf',
  title: 'The Shelf as Argument',
  author: 'A. Sample',
  cover: null,
  pageCount: 12,
  sizeBytes: 24_000,
}

const SAMPLE_EPUB: IndexedBook = {
  id: SAMPLE_EPUB_ID,
  path: SAMPLE_FILES[SAMPLE_EPUB_ID]!,
  format: 'epub',
  title: 'The Shelf as Argument, unbound',
  author: 'A. Sample',
  cover: null,
  // An EPUB has no page count until it is set in type — see `epubPages.ts` —
  // which is why the index has always left this null for them.
  pageCount: null,
  sizeBytes: 11_000,
}

const PLACEHOLDERS: IndexedBook[] = buildCatalogue(PLACEHOLDER_COUNT).map((book, i) => ({
  id: book.id,
  path: `placeholder://${book.id}`,
  format: i % 4 === 0 ? 'epub' : 'pdf',
  title: book.title,
  author: book.author,
  cover: null,
  pageCount: 80 + ((i * 37) % 400),
  sizeBytes: 1024 * (200 + ((i * 13) % 4000)),
}))

/**
 * Stand-in records and pictures, so the record shelf and the picture frames are
 * furnished in the browser build rather than standing conspicuously empty.
 *
 * The records are openly fake — their paths point at nothing, and the player
 * only ever touches a file when you actually put one on, so nothing here
 * fetches anything. The pictures are real, in that they are SVG data URLs
 * generated here: no network, no assets, and a frame with something in it.
 */
const RECORD_TITLES: [string, string][] = [
  ['Wild Is the Wind', 'Nina Simone'],
  ['Kind of Blue', 'Miles Davis'],
  ['Music for Airports', 'Brian Eno'],
  ['The Köln Concert', 'Keith Jarrett'],
  ['Blue', 'Joni Mitchell'],
  ['A Love Supreme', 'John Coltrane'],
  ['Spiegel im Spiegel', 'Arvo Pärt'],
  ['Selected Ambient Works', 'Aphex Twin'],
]

const PLACEHOLDER_TRACKS: IndexedTrack[] = RECORD_TITLES.map(([title, artist], i) => ({
  id: `record-${i}`,
  path: `placeholder://${title}`,
  title,
  artist,
  album: title,
  format: i % 3 === 0 ? 'flac' : 'mp3',
  sizeBytes: 8_000_000 + i * 400_000,
}))

/** A flat abstract print, as a data URL. Deterministic, so screenshots match. */
function placeholderPicture(index: number): string {
  const palettes = [
    ['#2f4257', '#7d3b32', '#d8c9a8'],
    ['#3f5a4a', '#8a7350', '#e2ddcb'],
    ['#5a3a55', '#b08d57', '#efe6d5'],
  ]
  const [ink, accent, paper] = palettes[index % palettes.length]!
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300">
    <rect width="400" height="300" fill="${paper}"/>
    <circle cx="${120 + index * 37}" cy="130" r="72" fill="${accent}" opacity="0.85"/>
    <rect x="40" y="196" width="320" height="10" fill="${ink}"/>
    <rect x="40" y="216" width="${180 + index * 20}" height="6" fill="${ink}" opacity="0.6"/>
  </svg>`
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`
}

const PLACEHOLDER_ARTWORK: IndexedArtwork[] = Array.from({ length: 3 }, (_, i) => ({
  id: `artwork-${i}`,
  path: placeholderPicture(i),
  title: ['Lake, morning', 'Pines', 'Study in ochre'][i]!,
}))

/**
 * Tapes for the crate beside the television.
 *
 * Their paths point at nothing, exactly as the placeholder records' do: taking
 * one out of the crate and putting it in the machine works, playback fails, and
 * the panel says why. That is the same failure a real `.mkv` gives in a WebView
 * that cannot decode it, so it is worth being able to walk into on purpose.
 */
const TAPE_TITLES: [string, string][] = [
  ['Holidays, 1998', 'Home'],
  ['The Lake, Spring', 'Home'],
  ['Stalker', 'Tarkovsky'],
  ['Solaris', 'Tarkovsky'],
  ['Le Samourai', 'Melville'],
  ['Wings of Desire', 'Wenders'],
  ['Paris, Texas', 'Wenders'],
  ['La Jetee', 'Marker'],
  ['Sans Soleil', 'Marker'],
  ['Koyaanisqatsi', 'Reggio'],
  ['Dersu Uzala', 'Kurosawa'],
  ['Ran', 'Kurosawa'],
]

const PLACEHOLDER_TAPES: IndexedTape[] = TAPE_TITLES.map(([title, series], i) => ({
  id: `tape-${i}`,
  path: `placeholder://${title}`,
  title,
  series,
  format: i % 4 === 0 ? 'webm' : 'mp4',
  sizeBytes: 700_000_000 + i * 11_000_000,
}))

/**
 * One ROM, and it is real — the Pong `npm run assets` writes into `public/`,
 * the same arrangement as the sample book. Real rather than a placeholder
 * because the whole arcade path — take the cartridge, slot it, the emulator
 * boots it, the screen lights — can then run under the headless smoke tests.
 */
export const SAMPLE_ROM_ID = 'sample-rom'
const SAMPLE_ROM_FILE = 'roms/pong.ch8'

const SAMPLE_ROMS: IndexedRom[] = [
  {
    id: SAMPLE_ROM_ID,
    path: SAMPLE_ROM_FILE,
    title: 'Pong',
    series: 'ch8',
    format: 'ch8',
    sizeBytes: 400,
  },
]

/**
 * Stand in for someone editing `library.json` and saving it.
 *
 * The browser build has no file to watch, so the world lives in localStorage and
 * the stamp is bumped by hand. That is what lets the smoke tests exercise live
 * reload and the reconciliation rules — which are the parts most likely to lose
 * somebody's arrangement, and so the parts most worth covering.
 */
export function setWorldText(text: string) {
  localStorage.setItem(WORLD_KEY, text)
  localStorage.setItem(WORLD_STAMP_KEY, `${text.length}:${nextStamp()}`)
}

let stampCounter = 0
const nextStamp = () => (stampCounter += 1)

export const browserDriver: LibraryService = {
  kind: 'browser',
  canPickFolder: false,
  canIndex: false,
  canFetchPapers: false,

  async getRoot() {
    return localStorage.getItem(ROOT_KEY)
  },

  async setRoot(path) {
    localStorage.setItem(ROOT_KEY, path)
  },

  async pickRoot() {
    return null
  },

  async scan() {
    return { found: PLACEHOLDERS.length, added: 0, unchanged: PLACEHOLDERS.length, removed: 0, failed: 0 }
  },

  onScanProgress() {
    return () => {}
  },

  async listBooks() {
    return [SAMPLE, SAMPLE_EPUB, ...PLACEHOLDERS]
  },

  async readBook(id) {
    const file = SAMPLE_FILES[id]
    if (!file) throw new UnsupportedOperation(`reading ${id}`, 'browser')
    const response = await fetch(file)
    // A missing sample means `npm run assets` has not run; say so rather than
    // handing pdf.js an HTML 404 page and letting it fail obscurely.
    if (!response.ok) throw new Error(`${file} is missing — run \`npm run assets\``)
    return new Uint8Array(await response.arrayBuffer())
  },

  async saveRenderedCover(id) {
    throw new UnsupportedOperation(`caching a cover for ${id}`, 'browser')
  },

  async fetchPaper(id) {
    // Not a network limit — a filesystem one. There is nowhere to put it.
    throw new UnsupportedOperation(`fetching ${id}`, 'browser')
  },

  async loadWorld() {
    return localStorage.getItem(WORLD_KEY)
  },

  async writeDefaultWorld(text) {
    if (localStorage.getItem(WORLD_KEY) !== null) return false
    setWorldText(text)
    return true
  },

  async worldStamp() {
    return localStorage.getItem(WORLD_STAMP_KEY)
  },

  async savePaths() {
    // There is no filesystem here; name the storage honestly rather than
    // inventing a path that does not exist. On the desktop these are
    // `<your library folder>/.library/library.json` and `.../books.json`.
    return {
      world: 'localStorage: kleib3ry.world',
      layout: 'localStorage: kleib3ry.layout',
      annotations: 'localStorage: kleib3ry.annotations',
    }
  },

  async loadLayout() {
    const stored = localStorage.getItem(LAYOUT_KEY)
    if (!stored) return null
    try {
      return JSON.parse(stored) as LayoutDocument
    } catch {
      // A corrupt value would otherwise fail every launch from here on. An
      // unpacked library beats a permanently empty room.
      localStorage.removeItem(LAYOUT_KEY)
      return null
    }
  },

  async saveLayout(layout) {
    localStorage.setItem(LAYOUT_KEY, JSON.stringify(layout))
  },

  async listTracks() {
    return PLACEHOLDER_TRACKS
  },

  async listArtwork() {
    return PLACEHOLDER_ARTWORK
  },

  async listTapes() {
    return PLACEHOLDER_TAPES
  },

  async listRoms() {
    return SAMPLE_ROMS
  },

  async readRom(id) {
    if (id !== SAMPLE_ROM_ID) throw new UnsupportedOperation(`reading ${id}`, 'browser')
    const response = await fetch(SAMPLE_ROM_FILE)
    if (!response.ok) throw new Error(`${SAMPLE_ROM_FILE} is missing — run \`npm run assets\``)
    return new Uint8Array(await response.arrayBuffer())
  },

  async loadAmbience() {
    const stored = localStorage.getItem(AMBIENCE_KEY)
    if (!stored) return null
    try {
      return JSON.parse(stored) as AmbienceState
    } catch {
      localStorage.removeItem(AMBIENCE_KEY)
      return null
    }
  },

  async saveAmbience(state) {
    localStorage.setItem(AMBIENCE_KEY, JSON.stringify(state))
  },

  async loadAnnotations() {
    const stored = localStorage.getItem(ANNOTATIONS_KEY)
    if (!stored) return null
    try {
      return JSON.parse(stored) as AnnotationsDocument
    } catch {
      localStorage.removeItem(ANNOTATIONS_KEY)
      return null
    }
  },

  async saveAnnotations(doc) {
    localStorage.setItem(ANNOTATIONS_KEY, JSON.stringify(doc))
  },

  // No filesystem; the settings card offers the digest as a download.
  async exportAnnotationsMarkdown() {
    return null
  },

  assetUrl(path) {
    return path
  },
}
